### ISSUE TITLE
perhaps a name change

### ISSUE THREAD

**Issue by steverweber** [jfindlay/pyNaCl#1]
pynacl is already a project, does almost the same thing as python libnacl.

perhaps pytweetnacl or something.

**Comment by jfindlay** [comment]
@steverweber, what do you think about pure_pynacl?  Is it too awkward?  I would like to do more than just the tweetnacl redux.  Also related: https://github.com/mdempsky/dnscurve/tree/master/slownacl.

**Comment by steverweber** [comment]
looks good to me.

**Comment by jfindlay** [comment]
cool
